version: "3.3"

services:
  api_ticker:
    build: .
    image: mixnet-state
    labels:
      - traefik.http.routers.api_ticker.entrypoints=websecure
      - traefik.http.routers.api_ticker.rule=Host(`isnymdown.notrustverify.ch`)
      - traefik.http.routers.api_ticker.tls=true
      - traefik.http.routers.api_ticker.tls.certresolver=letsEncrypt
      - traefik.enable=true
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - ./data.db:/data.db

networks:
   traefik-proxy:
      external: true

