#Create ubuntu as base image
FROM python
WORKDIR /

#Install packages
#RUN ["apt-get", "update", "-y"]
#RUN ["apt-get", "install","vim", "python3", "python3-pip",  "ca-certificates" ,"curl", "gnupg" ,"lsb-release", "git" ,"-y"]
RUN ["pip", "install", "pipenv"]
COPY Pipfile Pipfile.lock state.py db.py mixnet.py updateState.py utils.py /
RUN ["pipenv", "install", "--system", "--deploy","--ignore-pipfile" ]
CMD python updateState.py
ENV PYTHONUNBUFFERED 1