version: "3.3"

services:
  mixnet_state:
    build: .
    image: mixnet-state
    labels:
      - traefik.http.routers.mixnet_state.entrypoints=websecure
      - traefik.http.routers.mixnet_state.rule=Host(`isnymdown.notrustverify.ch`)
      - traefik.http.routers.mixnet_state.tls=true
      - traefik.http.routers.mixnet_state.tls.certresolver=letsEncrypt
      - traefik.enable=true
    restart: unless-stopped
    env_file: .env
    ports:
      - 5003:5002
    networks:
      - traefik-proxy
    volumes:
      - ./data/data.db:/data/data.db

networks:
   traefik-proxy:
      external: true

